/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowserEvent {
    /// Event type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Event timestamp (epoch milliseconds)
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// Event-specific data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl BrowserEvent {
    pub fn new(r#type: Type, timestamp: i32) -> BrowserEvent {
        BrowserEvent {
            r#type,
            timestamp,
            data: None,
        }
    }
}
/// Event type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "workspace-changed")]
    WorkspaceChanged,
}

impl Default for Type {
    fn default() -> Type {
        Self::WorkspaceChanged
    }
}

